// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1732901261);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1732901261);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1732901254390");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1732903056390");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1732901236002");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1732922836002");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241121140525");
user_pref("extensions.lastAppVersion", "133.0");
user_pref("extensions.lastPlatformVersion", "133.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.readerview@mozac.org", true);
user_pref("extensions.webextensions.uuids", "{\"webcompat@mozilla.org\":\"a9a6483e-8a59-44b4-83bd-ced3121d6c15\",\"icons@mozac.org\":\"26b21c56-4c4f-465f-a946-e272d36faf2a\",\"ads@mozac.org\":\"4d3eb7e7-0558-4287-8fd5-c03f40347833\",\"cookies@mozac.org\":\"aac71ddd-a0fb-4a16-8d98-0fb70af4ed91\",\"fxa@mozac.org\":\"fe954273-e40d-43ab-8dcb-5a5dcae17777\",\"readerview@mozac.org\":\"5af12de0-b511-464b-bf2c-8f02bfd5057c\"}");
user_pref("gfx-shader-check.build-version", "20241121140525");
user_pref("gfx-shader-check.device-id", "Mali-G78");
user_pref("gfx-shader-check.driver-version", "OpenGL ES 3.2 v1.r43p0-01eac0.5921042d0e5e9dcd76a86245576b4911");
user_pref("gfx-shader-check.ptr-size", 8);
user_pref("gfxinfo.cache.12.appver", "133.0");
user_pref("gfxinfo.cache.12.osver", 234881024);
user_pref("gfxinfo.cache.12.value", 1);
user_pref("gfxinfo.cache.16.appver", "133.0");
user_pref("gfxinfo.cache.16.osver", 234881024);
user_pref("gfxinfo.cache.16.value", 1);
user_pref("gfxinfo.cache.17.appver", "133.0");
user_pref("gfxinfo.cache.17.osver", 234881024);
user_pref("gfxinfo.cache.17.value", 1);
user_pref("idle.lastDailyNotification", 1732901422);
user_pref("intl.accept_languages", "en-US");
user_pref("intl.locale.requested", "en-US");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1732901422584");
user_pref("services.settings.blocklists.addons-bloomfilters.last_check", 1732901258);
user_pref("services.settings.blocklists.gfx.last_check", 1732901258);
user_pref("services.settings.clock_skew_seconds", 2);
user_pref("services.settings.last_etag", "\"1732895997209\"");
user_pref("services.settings.last_update_seconds", 1732901258);
user_pref("services.settings.main.addons-manager-settings.last_check", 1732901258);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1732901258);
user_pref("services.settings.main.fingerprinting-protection-overrides.last_check", 1732901258);
user_pref("services.settings.main.partitioning-exempt-urls.last_check", 1732901258);
user_pref("services.settings.main.password-recipes.last_check", 1732901258);
user_pref("services.settings.main.tracking-protection-lists.last_check", 1732901258);
user_pref("services.settings.main.translations-models.last_check", 1732901258);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1732901258);
user_pref("services.settings.main.url-parser-default-unknown-schemes-interventions.last_check", 1732901258);
user_pref("services.settings.security-state.cert-revocations.last_check", 1732901258);
user_pref("services.settings.security-state.intermediates.last_check", 1732901258);
user_pref("services.settings.security-state.onecrl.last_check", 1732901258);
user_pref("storage.vacuum.last.index", 0);
user_pref("toolkit.startup.last_success", 1732901229);
user_pref("toolkit.telemetry.cachedClientID", "df3e3cf9-2f62-4c33-ac6b-9307274f5b66");
user_pref("toolkit.telemetry.cachedProfileGroupID", "cde92cee-f84e-4b70-8b0a-7ca9d457a1d1");
